### ISSUE TITLE
date knob passes timestamp (number) instead of Date object

### ISSUE THREAD

**Issue by shilman** [storybookjs/addon-knobs#33]
<a href="https://github.com/jardakotesovec"><img src="https://avatars0.githubusercontent.com/u/1590681?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jardakotesovec](https://github.com/jardakotesovec)**
_Thursday Oct 27, 2016 at 16:19 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-knobs/issues/68_

----

Is that intention? I would expect that inside component I will receive Date object and not timestamp.

**Comment by Darkmift** [comment]
why was this closed?!
