### ISSUE TITLE
Add peer dependency for React 18 [Bug]

### ISSUE THREAD

**Issue by jasperswart** [storybookjs/addon-knobs#46]
### Expected behavior
peer dependency for React 18

### Screenshots and/or logs

If applicable, add screenshots and/or logs to help explain your problem.

### Environment

 - Node.js version: 16
 - NPM version: [e.g. 6.14.4]
 - Browser any
 - Browser version any
 - Device command line error
 - 
### Additional context

At the moment this bug is causing our library of react components to still be reactc17.

This is a breaking issue for us!

**Comment by literalpie** [comment]
I believe this was fixed in #48
